# Generated by Codex for GoGuest workspace intake.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.db.models.functions.text
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0127_workspace_sso_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceIntake",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, verbose_name="Workspace Intake Description")),
                ("is_default", models.BooleanField(default=False)),
                ("view_props", models.JSONField(default=dict)),
                ("logo_props", models.JSONField(default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workspaceintake_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workspaceintake_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_intakes",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace Intake",
                "verbose_name_plural": "Workspace Intakes",
                "db_table": "workspace_intakes",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="WorkspaceIntakeIssue",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description_json", models.JSONField(blank=True, default=dict)),
                ("description_html", models.TextField(blank=True, default="<p></p>")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("urgent", "Urgent"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(-2, "Pending"), (-1, "Rejected"), (0, "Snoozed"), (1, "Accepted"), (2, "Duplicate")],
                        default=-2,
                    ),
                ),
                ("snoozed_till", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                ("source", models.CharField(blank=True, default="IN_APP", max_length=255, null=True)),
                ("source_email", models.TextField(blank=True, null=True)),
                ("external_source", models.CharField(blank=True, max_length=255, null=True)),
                ("external_id", models.CharField(blank=True, max_length=255, null=True)),
                ("extra", models.JSONField(default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workspaceintakeissue_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "duplicate_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="db.workspaceintakeissue",
                    ),
                ),
                (
                    "intake",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="db.workspaceintake",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workspace_intake_source",
                        to="db.issue",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workspaceintakeissue_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_intake_issues",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "WorkspaceIntakeIssue",
                "verbose_name_plural": "WorkspaceIntakeIssues",
                "db_table": "workspace_intake_issues",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="workspaceintake",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                "workspace",
                condition=models.Q(("deleted_at__isnull", True)),
                name="workspace_intake_unique_lower_name_workspace_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspaceintake",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("is_default", True)),
                fields=("workspace",),
                name="workspace_intake_one_default_per_workspace_active",
            ),
        ),
    ]
