# Generated by Codex for GoGuest intake custom forms.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0128_workspace_intake"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntakeFormField",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("label", models.CharField(max_length=255)),
                ("placeholder", models.CharField(blank=True, max_length=255)),
                ("help_text", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("short_text", "Short text"),
                            ("long_text", "Long text"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("boolean", "Boolean"),
                            ("select", "Select"),
                            ("multi_select", "Multi-select"),
                            ("file", "File"),
                            ("user", "User"),
                        ],
                        max_length=32,
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                ("is_required", models.BooleanField(default=False)),
                ("relative_order", models.PositiveIntegerField(default=65535)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intakeformfield_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "intake",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_fields",
                        to="db.intake",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intake_form_fields",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intakeformfield_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intake_form_fields",
                        to="db.workspace",
                    ),
                ),
                (
                    "workspace_intake",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_fields",
                        to="db.workspaceintake",
                    ),
                ),
            ],
            options={
                "verbose_name": "IntakeFormField",
                "verbose_name_plural": "IntakeFormFields",
                "db_table": "intake_form_fields",
                "ordering": ("relative_order", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="IntakeFormFieldOption",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("label", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                ("relative_order", models.PositiveIntegerField(default=65535)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intakeformfieldoption_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="db.intakeformfield",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intakeformfieldoption_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "IntakeFormFieldOption",
                "verbose_name_plural": "IntakeFormFieldOptions",
                "db_table": "intake_form_field_options",
                "ordering": ("relative_order", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="IntakeFormFieldValue",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("value_text", models.TextField(blank=True)),
                ("value_number", models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ("value_datetime", models.DateTimeField(blank=True, null=True)),
                ("value_boolean", models.BooleanField(blank=True, null=True)),
                ("value_file_url", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intakeformfieldvalue_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="db.intakeformfield",
                    ),
                ),
                (
                    "intake_issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_values",
                        to="db.intakeissue",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intake_form_values",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intakeformfieldvalue_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "value_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="single_values",
                        to="db.intakeformfieldoption",
                    ),
                ),
                (
                    "value_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intake_form_values",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intake_form_values",
                        to="db.workspace",
                    ),
                ),
                (
                    "workspace_intake_issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_values",
                        to="db.workspaceintakeissue",
                    ),
                ),
            ],
            options={
                "verbose_name": "IntakeFormFieldValue",
                "verbose_name_plural": "IntakeFormFieldValues",
                "db_table": "intake_form_field_values",
                "ordering": ("field__relative_order", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="IntakeFormFieldValueOption",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intakeformfieldvalueoption_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multi_values",
                        to="db.intakeformfieldoption",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intakeformfieldvalueoption_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_options",
                        to="db.intakeformfieldvalue",
                    ),
                ),
            ],
            options={
                "verbose_name": "IntakeFormFieldValueOption",
                "verbose_name_plural": "IntakeFormFieldValueOptions",
                "db_table": "intake_form_field_value_options",
            },
        ),
        migrations.AddConstraint(
            model_name="intakeformfield",
            constraint=models.CheckConstraint(
                check=(
                    models.Q(("workspace_intake__isnull", False), ("intake__isnull", True))
                    | models.Q(("workspace_intake__isnull", True), ("intake__isnull", False))
                ),
                name="intake_form_field_one_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="intakeformfieldoption",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("field", "value"),
                name="intake_form_option_unique_value_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="intakeformfieldvalue",
            constraint=models.CheckConstraint(
                check=(
                    models.Q(("workspace_intake_issue__isnull", False), ("intake_issue__isnull", True))
                    | models.Q(("workspace_intake_issue__isnull", True), ("intake_issue__isnull", False))
                ),
                name="intake_form_value_one_ticket",
            ),
        ),
        migrations.AddConstraint(
            model_name="intakeformfieldvalue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("workspace_intake_issue__isnull", False)),
                fields=("field", "workspace_intake_issue"),
                name="intake_form_value_unique_ws_issue_field",
            ),
        ),
        migrations.AddConstraint(
            model_name="intakeformfieldvalue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("intake_issue__isnull", False)),
                fields=("field", "intake_issue"),
                name="intake_form_value_unique_project_issue_field",
            ),
        ),
        migrations.AddConstraint(
            model_name="intakeformfieldvalueoption",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("value", "option"),
                name="intake_form_value_option_unique_active",
            ),
        ),
    ]
