# Generated by Codex on 2026-05-12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0132_issue_custom_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="projecttemplate_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="projecttemplate_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
                ("project", models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name="project_projecttemplate", to="db.project")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workspace_projecttemplate", to="db.workspace")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("icon_props", models.JSONField(blank=True, default=dict)),
                ("payload", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Project Template",
                "verbose_name_plural": "Project Templates",
                "db_table": "project_templates",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="projecttemplate",
            index=models.Index(fields=["workspace"], name="project_template_ws_idx"),
        ),
        migrations.AddConstraint(
            model_name="projecttemplate",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                "workspace",
                condition=models.Q(("deleted_at__isnull", True)),
                name="project_template_unique_ws_name_ci",
            ),
        ),
    ]
